# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser-pro" do
  version "2.15.2"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
      sha256 "0399c8f5b895ebb00524d7bd973937afb0f185142b24de40a0c032e13a3482b4"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
      sha256 "a7cee9cc5fada42d17ee033924535b0e508f654db6f3734e67776b7722c274d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
      sha256 "61baf60a947158bdd5be73b474943483dc97cde5bad99206e999beb2532c4247"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
      sha256 "cc6cc50a101e7f5cec645503555b39ac330b484513fd30fbf3b18245c57d57bc"
    end
  end

  name "goreleaser-pro"
  desc "Release engineering, simplified."
  homepage "https://goreleaser.com"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "goreleaser",
    ]

  binary "goreleaser"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  fish_completion "completions/goreleaser.fish"
  zsh_completion "completions/goreleaser.zsh"

  # No zap stanza required

end
