# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser" do
  desc "Release engineering, simplified"
  homepage "https://goreleaser.com"
  version "2.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  zsh_completion "completions/goreleaser.zsh"
  fish_completion "completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/goreleaser/releases/download/v2.11.1/goreleaser_Darwin_x86_64.tar.gz"
      sha256 "0ab78afc49884c9f65f5a63273470058337d8b1ff5b335b9727d1f32f83ad6b6"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser/releases/download/v2.11.1/goreleaser_Darwin_arm64.tar.gz"
      sha256 "b1cfa3a0ade75e7a5d8ccd81219675999b9976f26f133c6a4d12aa80145a88e9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/goreleaser/releases/download/v2.11.1/goreleaser_Linux_x86_64.tar.gz"
      sha256 "a01e2e9b72d9ee922361ef05263cf6fa77db4686df861b2b0d43713919c495c0"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser/releases/download/v2.11.1/goreleaser_Linux_arm64.tar.gz"
      sha256 "f0d3085a62898bf562177e5e5199dd83965df5f0495b9fb495559ac06d83ed9d"
    end
  end

  conflicts_with cask: [
      "goreleaser-pro",
    ],
    formula: [
      "goreleaser",
      "goreleaser-pro",
    ]

  # No zap stanza required
end
