# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser" do
  name "goreleaser"
  desc "Release engineering, simplified"
  homepage "https://goreleaser.com"
  version "2.14.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  zsh_completion "completions/goreleaser.zsh"
  fish_completion "completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/goreleaser/releases/download/v#{version}/goreleaser_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "d8fcc408826058986df90950ce2824ed037e57e3229eb23dcf0badc8d23123bc"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser/releases/download/v#{version}/goreleaser_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "6dae42fecaed39f36d0ac9ce98f36ee14804e483f5c1446e205796ac91b7be4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/goreleaser/releases/download/v#{version}/goreleaser_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "dc7faeeeb6da8bdfda788626263a4ae725892a8c7504b975c3234127d4a44579"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser/releases/download/v#{version}/goreleaser_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "581a10e53c1176b3e81ee45cf531e02dbf899db0bc7b795669347df4276ce948"
    end
  end

  conflicts_with cask: [
      "goreleaser-pro",
    ]

  # No zap stanza required
end
