# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser-mcp@0" do
  name "goreleaser-mcp@0"
  desc "GoReleaser MCP server"
  homepage "https://goreleaser.com/mcp"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser-mcp"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "a68e072d386568d4535e629d94fc38c450d72b37299a541e23398e5bf6949b8c"
    end
    on_arm do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "92982469b88566c8f734c1168bb837d7ce3146705c1559c5fe04d3aa25a8a8c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "4587d5625077dc3a658be081aa353b2fcf5eb9b054e21ec4a9711f9e89cb201c"
    end
    on_arm do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "412a60fcb48a2fe46d263ec3316fa72b578b020e6d9d4df8b6de0ab1c17c04f5"
    end
  end

  # No zap stanza required
end
