# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser-pro" do
  desc "Release engineering, simplified."
  homepage "https://goreleaser.com"
  version "2.10.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser-pro"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  zsh_completion "completions/goreleaser.zsh"
  fish_completion "completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.10.1/goreleaser-pro_Darwin_x86_64.tar.gz"
      sha256 "6986fc489bf6d88bbe2dd04c97b558c4e042089f04191903dbc9274cc1f93a79"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.10.1/goreleaser-pro_Darwin_arm64.tar.gz"
      sha256 "4f3933d57d4c7bfff62f91016ea6cd2318517684b5b8e9edc8ef84ccd5cd9da7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.10.1/goreleaser-pro_Linux_x86_64.tar.gz"
      sha256 "12340f005815b0df164f8b0edef47a199ce06219ba232e61343bbfdd29e42ca1"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v2.10.1/goreleaser-pro_Linux_arm64.tar.gz"
      sha256 "ea01642e494b7e790d6c3543a4bc693fb561dd3d4d7ae59faa583727923a79d9"
    end
  end

  conflicts_with: cask: [
                    goreleaser-pro
                  ],
                  formula: [
                    goreleaser,
                    goreleaser-pro
                  ]

  # No zap stanza required
end
