# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser-pro@2" do
  name "goreleaser-pro@2"
  desc "Release engineering, simplified."
  homepage "https://goreleaser.com"
  version "2.12.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  zsh_completion "completions/goreleaser.zsh"
  fish_completion "completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "c8f18ac0cdd34518481aca4c23846ec037232de4b8527f5772abd995a9918604"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "f40b137e4058b4d0727bde4d9ae19f428d81b22a5d6552164254cbba82701547"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "6b87bfd54eb23371c6576228ac7dcee31395d2d0539022ba285d7f7c6e1ec737"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "3b2291d4909e764143fa15f7da40c0f2a3cd02d8fccf5a80be26957016bc19fb"
    end
  end

  conflicts_with cask: [
      "goreleaser",
    ]

  # No zap stanza required
end
