# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser-pro" do
  version "2.15.4"

  on_macos do
    on_intel do
      sha256 "0f115ca6678220e06df496c112b7c86f0e059b4e64832f5fce97e31c9027bea0"
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
    end
    on_arm do
      sha256 "f48b6ce7d17d959a2fdb033ece22c09e90e12956cac9c6ab40a7cfe6d6d202d3"
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "a7902f82d5afdcc2f43d5333d0f9d77db2d2c261b33189182c5358fc2f0bc1dc"
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
    end
    on_arm do
      sha256 "c2714766cd73d45997e10397cf9ed889ef17761e9ffdcb72f179fec605d6155f"
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser-pro/releases/download"
    end
  end

  name "goreleaser-pro"
  desc "Release engineering, simplified."
  homepage "https://goreleaser.com"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "goreleaser",
    ]

  binary "goreleaser"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  fish_completion "completions/goreleaser.fish"
  zsh_completion "completions/goreleaser.zsh"

  # No zap stanza required

end
