# This file was generated by GoReleaser. DO NOT EDIT.
cask "goreleaser-pro@2" do
  name "goreleaser-pro@2"
  desc "Release engineering, simplified."
  homepage "https://goreleaser.com"
  version "2.12.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser"
  manpage "manpages/goreleaser.1.gz"
  bash_completion "completions/goreleaser.bash"
  zsh_completion "completions/goreleaser.zsh"
  fish_completion "completions/goreleaser.fish"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "308ecc3bd6f8528d1053e989ab833bde4104fb5c78eb592b9a63f7d7fb2f035b"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "fc0d789087b10c021e8bbbdef63c854aabc5cda181c8f77c3f115c8c06e33553"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "d80dcadd52ab93d640213e1ef2a24007e7a84e52a351e9275bb9061bfa873be8"
    end
    on_arm do
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v#{version}/goreleaser-pro_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/goreleaser/releases/download"
      sha256 "d28b871c86b8493145dd6ecbe2a653a14f5d95a08c77153f98ebf1879dab0581"
    end
  end

  conflicts_with cask: [
      "goreleaser",
    ]

  # No zap stanza required
end
