# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp" do
  name "mcp"
  desc "GoReleaser MCP server"
  homepage "https://goreleaser.com/mcp"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/mcp_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "f4892247ebcb49f483afbd5d8393316302b11e8af3533ee2177c5f393b6323b5"
    end
    on_arm do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/mcp_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "81474379880245327b856ccc79401bf4bfa56d42800a38aafdee60d2585ec01e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/mcp_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "4d2e66a34cfc9e9305669ff0fdd872c62ae86d128d0d5c924f2f2c563005f992"
    end
    on_arm do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/mcp_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "58d7963ea3b4a95fb198245106d5aa9a1239ad5ff419ed0f10a6379fec962a7b"
    end
  end

  # No zap stanza required
end
