# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "179fafaf0976bd6d3ecae633fd50d3da9584be207e72ff968d5fedaa1ce058c8"
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
    end
    on_arm do
      sha256 "bab6401b68428d37b7e156ef2ad3fa89220ad1856865007437e752e803673c76"
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "6fcb5f146502eed97ff11a63a40993746fe20be515331f626d40b5fc60965602"
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
    end
    on_arm do
      sha256 "b21cc2ca97c6bebdbccf187a0a751bd78d092547c48be59a28a9a2b115b5ca55"
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
    end
  end

  name "mcp"
  desc "GoReleaser MCP server"
  homepage "https://goreleaser.com/mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goreleaser-mcp"

  # No zap stanza required

end
