# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp" do
  name "mcp"
  desc "GoReleaser MCP server"
  homepage "https://goreleaser.com/mcp"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Darwin_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "1f120b7eb975b51bc3048e137bd0708e13e322cb19ef1ee1fe51808e0a2bc98d"
    end
    on_arm do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "3532a93ad1e8327b51cb73aa1e772439335af7396ae3514a7e8eefbdbf7e8c9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Linux_x86_64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "16c8734eba4729fa31e2e4e097cb56d8b0afb33752aae4deb481ebcfe95a62b5"
    end
    on_arm do
      url "https://github.com/goreleaser/mcp/releases/download/v#{version}/goreleaser-mcp_Linux_arm64.tar.gz",
        verified: "github.com/goreleaser/mcp/releases/download"
      sha256 "a40ed1fbce5e209c8f91412cb821fa552673f79b21448eabf754af0c73d18227"
    end
  end

  # No zap stanza required
end
