# This file was generated by GoReleaser. DO NOT EDIT.
cask "sponsors" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_darwin_amd64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "6b35e75d79f7e4d56c38a4d3f701968660e98b731b24228813e15903125e1eed"
      rename "sponsors_darwin_amd64/sponsors", "sponsors"
    end
    on_arm do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "27e1134ba4c4a737f8ea1e88875c5c1d2ed123aff4f8edb8741924d38214c7a8"
      rename "sponsors_darwin_arm64/sponsors", "sponsors"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_linux_amd64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "4407575689fe363d7895d77961c82960c6413944284cf094c50786ddd35b4759"
      rename "sponsors_linux_amd64/sponsors", "sponsors"
    end
    on_arm do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_linux_arm64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "79877d07beeff8caec7a3931bdf27b5af581a72279d0c500fabab5f2451a045d"
      rename "sponsors_linux_arm64/sponsors", "sponsors"
    end
  end

  name "sponsors"
  desc "Fetches sponsors from multiple sources and renders them based on templates"
  homepage "https://goreleaser.com/sponsors"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sponsors"

  # No zap stanza required

end
