# This file was generated by GoReleaser. DO NOT EDIT.
cask "sponsors" do
  version "0.3.4"

  on_macos do
    on_intel do
      sha256 "8b0e45f2300485f728c5cd51da48c397fab90aabb1cee11b8402a3b67fef8021"
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_darwin_amd64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      rename "sponsors_darwin_amd64/sponsors", "sponsors"
    end
    on_arm do
      sha256 "ddd2a3d3c34302c7ce13c94037647c2d2deded0dad52bb3418267b4e47cef500"
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      rename "sponsors_darwin_arm64/sponsors", "sponsors"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ab15d70f20b1ec6dff637b138d061e892508a0d12272b2de7f0a0978635334f"
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_linux_amd64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      rename "sponsors_linux_amd64/sponsors", "sponsors"
    end
    on_arm do
      sha256 "92e18e842c1a014b6240947290dbfa6c9b3f7818c18c8ecc6297970aaf4908df"
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_linux_arm64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      rename "sponsors_linux_arm64/sponsors", "sponsors"
    end
  end

  name "sponsors"
  desc "Fetches sponsors from multiple sources and renders them based on templates"
  homepage "https://goreleaser.com/sponsors"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sponsors"

  # No zap stanza required

end
