# This file was generated by GoReleaser. DO NOT EDIT.
cask "sponsors" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_darwin_amd64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "15b7ac94286cbf1b62ccbc2818930b01bc6036e6ce35076c2648d7d98fe684e4"
      rename "sponsors_darwin_amd64/sponsors", "sponsors"
    end
    on_arm do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_darwin_arm64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "d6b15aaa49849e8032cd723c5ca26dbb645cb6f196f0b3cd7ff0c26ca35d6c2d"
      rename "sponsors_darwin_arm64/sponsors", "sponsors"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_linux_amd64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "4766c2a50e737dbf14fdcf6ec7c0eee1b06dc274d46f8dda674c896842eb0b87"
      rename "sponsors_linux_amd64/sponsors", "sponsors"
    end
    on_arm do
      url "https://github.com/goreleaser/sponsors/releases/download/v#{version}/sponsors_linux_arm64.tar.gz",
        verified: "github.com/goreleaser/sponsors/releases/download"
      sha256 "37d2267e4508713d459e424916b83c7b1e6a5d9d11ef1f0ed0e7ed661b3d6cae"
      rename "sponsors_linux_arm64/sponsors", "sponsors"
    end
  end

  name "sponsors"
  desc "Fetches sponsors from multiple sources and renders them based on templates"
  homepage "https://goreleaser.com/sponsors"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sponsors"

  # No zap stanza required

end
