# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Example2 < Formula
  desc "Test formula, do not use it"
  homepage "https://gitlab.com/goreleaser/example"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/goreleaser/example-cross-publish/-/releases/v0.1.7/downloads/example-2_0.1.7_darwin_amd64.tar.gz"
      sha256 "6169ae4e3962f2022804f6855db31611ebf1994f8b15063f0abd4b7e5b32c250"

      def install
        bin.install "example-2"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/goreleaser/example-cross-publish/-/releases/v0.1.7/downloads/example-2_0.1.7_darwin_arm64.tar.gz"
      sha256 "2894ef65abe34316a262f98b1f0a9327da50b2314720ed4111776f1052fb1a3b"

      def install
        bin.install "example-2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gitlab.com/goreleaser/example-cross-publish/-/releases/v0.1.7/downloads/example-2_0.1.7_linux_amd64.tar.gz"
      sha256 "3b472e75e6e18899fca1aa11b6d7cf34367eaec319a560b4ac4a77dbbfceb2fc"

      def install
        bin.install "example-2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/goreleaser/example-cross-publish/-/releases/v0.1.7/downloads/example-2_0.1.7_linux_arm64.tar.gz"
      sha256 "4f0bd9b7418370f7d9e827014327982f167a2035cccbe8dec2f4c4f1d042335b"

      def install
        bin.install "example-2"
      end
    end
  end
end
