# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPro < Formula
  desc "Deliver Go binaries as fast and easily as possible"
  homepage "https://goreleaser.com"
  version "0.169.0-pro"
  license "Copyright Becker Software LTDA"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v0.169.0-pro/goreleaser-pro_Darwin_x86_64.tar.gz"
      sha256 "dc31f6ca1f0468491ae0e416d9250579fb6ab23fa218a15df4a7bccb68879973"
    end
    if Hardware::CPU.arm?
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v0.169.0-pro/goreleaser-pro_Darwin_arm64.tar.gz"
      sha256 "9770ff1a920e4db1c4d0a38e1a5ca9436c43f362cfff6ab9b6120235f7dabf42"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v0.169.0-pro/goreleaser-pro_Linux_x86_64.tar.gz"
      sha256 "0a6ffa7fec796d3c3ef814c64be01744c3b034cb8d9fe83d7732685d801c068f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v0.169.0-pro/goreleaser-pro_Linux_armv6.tar.gz"
      sha256 "b5edd98e7296151aba707ccc6dc52d8a1cccc3c2fc23a2ecf064a5cec359004f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goreleaser/goreleaser-pro/releases/download/v0.169.0-pro/goreleaser-pro_Linux_arm64.tar.gz"
      sha256 "cbd25fac8c95c4c818ff1f42761f5c7f86c23f591eca55784ba108639dbdfd99"
    end
  end

  depends_on "go" => :optional
  depends_on "git"

  conflicts_with "goreleaser"

  def install
    bin.install "goreleaser"
    bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
    fish_completion.install "completions/goreleaser.fish"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
