# This file was generated by GoReleaser. DO NOT EDIT.
class Goreleaser < Formula
  desc "Deliver Go binaries as fast and easily as possible"
  homepage "https://goreleaser.com"
  version "0.117.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/goreleaser/goreleaser/releases/download/v0.117.2/goreleaser_Darwin_x86_64.tar.gz"
    sha256 "922d824b2a6e333f4c1853cc61ade990de877581ccb10872ccc1ca0a28bbb8ab"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/goreleaser/goreleaser/releases/download/v0.117.2/goreleaser_Linux_x86_64.tar.gz"
      sha256 "1d2ddd59821f69b8168a3c4386821269e57bd18eedff0f68abf9c752b592a453"
    end
  end

  def install
    bin.install "goreleaser"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
