# This file was generated by GoReleaser. DO NOT EDIT.
class Nfpm < Formula
  desc "nFPM is not FPM"
  homepage "https://github.com/goreleaser/nfpm"
  url "https://github.com/goreleaser/nfpm/releases/download/v0.10.0/nfpm_0.10.0_Darwin_x86_64.tar.gz"
  version "0.10.0"
  sha256 "b6d94c412a2a36f05ad352870db3f595c8aa786610074e73b3cfec1b717a97ef"

  def install
    bin.install "nfpm"
  end

  test do
    system "#{bin}/nfpm -v"
  end
end
